// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var element, i, _i, _results;
    element = $('#select-floors-number');
    _results = [];
    for (i = _i = 1; _i <= 5; i = ++_i) {
      if (i === 5) {
        _results.push(element.append("<option value='" + i + "'>" + i + "+</option>"));
      } else {
        _results.push(element.append("<option value='" + i + "'>" + i + "</option>"));
      }
    }
    return _results;
  });

}).call(this);

//# sourceMappingURL=production.map
